//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordNepaliSpellCheck {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    public sealed partial class SpellSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SpellSettings defaultInstance = ((SpellSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SpellSettings())));
        
        public static SpellSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8085/spellSuggestion?query=")]
        public string remoteURL {
            get {
                return ((string)(this["remoteURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpellingService")]
        public string serviceName {
            get {
                return ((string)(this["serviceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://103.198.9.169/#/user/purchaseMsWordPlugin")]
        public string serviceRenewURL {
            get {
                return ((string)(this["serviceRenewURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://103.198.9.169/#/user/registerMsWordPlugin")]
        public string servicePaymentURL {
            get {
                return ((string)(this["servicePaymentURL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://103.198.9.169/saayak-web-interface/mutation")]
        public string userSuggestionURL {
            get {
                return ((string)(this["userSuggestionURL"]));
            }
            set {
                this["userSuggestionURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8085/spellSuggestion?query=")]
        public string pingURL {
            get {
                return ((string)(this["pingURL"]));
            }
            set {
                this["pingURL"] = value;
            }
        }
    }
}
